name: Update RUP INAPROC

on:
  schedule:
    - cron: "0 22 * * *"   # 05:00 WIB
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Buat folder data
        run: mkdir -p data

      - name: Download semua endpoint INAPROC
        run: |
          TOKEN="inprc7642391c38774272bf57ca25ac1d4544"
          BASE_URL="https://data.inaproc.id/api/legacy/rup"
          KODE="D228"
          TAHUN="2026"

          endpoints=(
            "paket-penyedia-terumumkan"
            "paket-swakelola-terumumkan"
            "master-satker"
            "program-master"
            "struktur-anggaran-pd"
          )

          for ep in "${endpoints[@]}"; do

            url="$BASE_URL/$ep?kode_klpd=$KODE&tahun=$TAHUN"
            filename="data/Legacy_${ep}_${TAHUN}.json"

            echo ""
            echo "==============================="
            echo "Download: $url"
            echo "Simpan ke: $filename"

            # request API
            response=$(curl -s -H "Authorization: Bearer $TOKEN" "$url")

            # ==============================
            # VALIDASI RESPONSE
            # ==============================

            if [ -z "$response" ]; then
              echo "Response kosong → buat file []"
              echo "[]" > $filename

            else
              # cek apakah valid JSON
              echo "$response" | jq . > $filename 2>/dev/null

              if [ $? -ne 0 ]; then
                echo "JSON tidak valid → fallback []"
                echo "[]" > $filename
              else
                echo "SUKSES"
              fi
            fi

          done

      - name: Commit & Push ke GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Update data RUP otomatis" || echo "Tidak ada perubahan"
          git push
