name: Update RUP Data

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare folder
        run: mkdir -p data

      - name: Download Data
        run: |
          curl -L "ISI_URL_PENYEDIA" -o data/Legacy_rup_paket-penyedia-terumumkan_2026.json
          curl -L "ISI_URL_SWAKELOLA" -o data/Legacy_rup_paket-swakelola-terumumkan_2026.json
          curl -L "ISI_URL_MASTER_SATKER" -o data/Legacy_rup_master-satker_2026.json
          curl -L "ISI_URL_PROGRAM" -o data/Legacy_rup_program-master_2026.json
          curl -L "ISI_URL_STRUKTUR" -o data/Legacy_rup_struktur-anggaran-pd_2026.json

      - name: Install Pandas
        run: pip install pandas

      - name: Run Python Script
        run: python generate.py

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*
          git commit -m "update data otomatis" || echo "no changes"
          git push
